#!/bin/bash

# ===================================================================
# Upload an R Shiny Application to remote.
# ===================================================================

# Checks config file for malicious code. Only allows key=value pairs.
# http://wiki.bash-hackers.org/howto/conffile#secure_it
CONFIG_FILE="config.cfg"
CONFIG_FILE_SECURED="config.cfg.tmp"

# Check if the file contains something we don't want
if egrep -q -v '^#|^[^ ]*=[^;]*' "$CONFIG_FILE"; then
  echo "Config file is unclean, cleaning it..." >&2
  # Filter the original to a new file
  egrep '^#|^[^ ]*=[^;&]*'  "$CONFIG_FILE" > "$CONFIG_FILE_SECURED"
  CONFIG_FILE="$CONFIG_FILE_SECURED"
  # Delete the temporary config file
  rm "$CONFIG_FILE_SECURED"
fi

# Load configuration file
source "$CONFIG_FILE"

# Set current directory and project names
PROJECT_NAME=${PWD##*/}
DIRECTORY=$(pwd)

# Delete existing project on the server
ssh $USERNAME@$SERVER "rm -rf $REMOTE_DIR/$PROJECT_NAME"
# Upload new project version
scp -r $DIRECTORY $USERNAME@$SERVER:$REMOTE_DIR

URL=http://$SERVER/users/$USERNAME/$PROJECT_NAME
echo "Project at: $URL"
